server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: publicaciones-service
          uri: lb://publicaciones-service
          predicates:
            - Path=/publicaciones/**
        - id: catalogo-service
          uri: lb://catalogo-service
          predicates:
            - Path=/catalogo/**
        - id: notificaciones-service
          uri: lb://notificaciones-service
          predicates:
            - Path=/notificaciones/**
    discovery:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/auth/.well-known/jwks.json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
   metrics:
     export:   
        enabled: true
