server:
  port: 9094 # Or another available port

spring:
  application:
    name: notificaciones-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: localhost
    port: 1025
    username: # No username needed for MailHog
    password: # No password needed for MailHog
    properties:
      mail:
        smtp:
          auth: false # No authentication needed
          starttls:
            enable: false # No TLS needed
  datasource:
    url: jdbc:postgresql://localhost:26258/notif_db # Assuming notif_db for notifications
    username: root
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true