server:
  port: 9091

spring:
  application:
    name: publicaciones-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/auth/.well-known/jwks.json

  datasource:
    url: jdbc:postgresql://localhost:26258/pub_db
    username: root
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
